name: Build, docs, checks, tests (generic x86-64 platform)

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install prerequisites
      run: sudo apt install -y libfl-dev xxd doxygen graphviz

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Source preamble checks
      run: ./scripts/check-source-preambles.py

    - name: Build and run tests (debug build)
      run: ./build-run-tests.sh generic

    - name: Build release binaries
      run: ./build-release.sh generic

    - name: Build Doxygen documentation
      run: ./build-docs.sh

    - name: Build GitHub pages contents
      run: ./build-github-pages.sh

    - name: Upload GitHub pages
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/github-pages/

  deploy:
    if: github.event_name != 'pull_request' && github.repository == 'skiminki/hoover-chess-utils' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
